### ISSUE TITLE
Alpha Release 0.0.1

### ISSUE THREAD

**Issue by LarryBattle** [LarryBattle/CordView#1]
## Goal
- Create a hello world in Java 11 using Spring Boot 2.3 and angular 9

## TODO
- [x] Create hello world rest api endpoint 
- [x] Create hello world web page using angular 9
- [x] Add integration tests
- [x] Add a architecture diagram for the requirements

**Comment by LarryBattle** [comment]
Done
