### ISSUE TITLE
Version 0.1.0 Add support for submitting a job posting 

### ISSUE THREAD

**Issue by LarryBattle** [LarryBattle/CordView#2]
## Requirements

As a JOB_POSTER I want to 

- [ ] 1. CRUD a job posting with the following data (job: {title, description, wage($/HR vs $/Per year)}, date posted) 
- [ ] 2. Access JOB_POSTER view

## Tasks
- [ ] Frontend: Create home page
- [ ] Frontend: Can submit job posting
- [ ] Server: Can create job posting
- [ ] DB: Setup seed data

**Comment by LarryBattle** [comment]
wont' do
